- name: Database configure
  connection: local
  gather_facts: no
  hosts: localhost
  tasks:
    - name: Create a random password
      command: pwgen -c -n -B 10 1
      register: randompw

    - name: Get environment vars
      set_fact:
        mariadb_database: "{{ lookup('env', 'MARIADB_DATABASE') | default('mysql', true) }}"
        mariadb_username: "{{ lookup('env', 'MARIADB_USERNAME') | default('admin', true) }}"
        mariadb_password: "{{ lookup('env', 'MARIADB_PASSWORD') | default('admin', true) }}"
        mariadb_root_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') | default(randompw.stdout, true) }}"
        wsrep_cluster_addresses: "{{ lookup('env', 'WSREP_CLUSTER_ADDRESSES') }}"
        wsrep_node_name: "{{ lookup('env', 'WSREP_NODE_NAME') }}"

    - name: create my.cnf
      template:
        src:  /setup/my.cnf.j2
        dest: /var/lib/mysql/my.cnf

